//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""2b5d2c62-40e4-4889-94ab-75b944b15753"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""e6f8723f-386b-4b0c-a703-f67b35f5948b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move2"",
                    ""type"": ""Value"",
                    ""id"": ""135829f2-281c-455e-bcca-8b541ded65cb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move3"",
                    ""type"": ""Value"",
                    ""id"": ""15c69c6f-c2c6-4e31-aee0-79064c6d97cd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move4"",
                    ""type"": ""Value"",
                    ""id"": ""cde3f25e-44c4-40f1-be1e-e570a4307b5c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""197c876d-0285-486f-9f6e-a26e47cfa208"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim2"",
                    ""type"": ""Value"",
                    ""id"": ""d9cb63df-ebfb-4545-a02d-3e1cc0050ab5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim3"",
                    ""type"": ""Value"",
                    ""id"": ""6c6b2c27-6d08-4878-87cd-c1aa88c94b62"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim4"",
                    ""type"": ""Value"",
                    ""id"": ""2ca6f03a-3dd8-43cd-8f1a-dc757c321d78"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""78e03480-e301-4f45-8443-a23e00c0c3b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump2"",
                    ""type"": ""Button"",
                    ""id"": ""b53a6da0-5704-4415-bac3-f79757ffe0e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump3"",
                    ""type"": ""Button"",
                    ""id"": ""37c1c807-1c88-41c1-8091-802608412688"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump4"",
                    ""type"": ""Button"",
                    ""id"": ""b430fa7e-0789-414d-ba62-58ce2d74f1e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""63bb4a02-ac4b-48e0-83e5-7c5830109c0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop2"",
                    ""type"": ""Button"",
                    ""id"": ""9836f99f-0d48-4a2c-ba67-fae2f1b47366"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop3"",
                    ""type"": ""Button"",
                    ""id"": ""64938df4-cd95-4e02-9039-82abbd222c19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop4"",
                    ""type"": ""Button"",
                    ""id"": ""369edeaa-cddd-4989-8954-8178aebbb8fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""e0a3044c-63db-420d-a6d3-7f90f771c7f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire2"",
                    ""type"": ""Button"",
                    ""id"": ""2924d106-0f24-4320-a92a-f63dd55eb7e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire3"",
                    ""type"": ""Button"",
                    ""id"": ""a7d8947f-4437-4396-aa13-67a2f5429cd4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire4"",
                    ""type"": ""Button"",
                    ""id"": ""e229b5f2-430e-464b-a093-4447e661593b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charge1"",
                    ""type"": ""Button"",
                    ""id"": ""c8716fc3-41f1-40c4-ab1a-92bb19aed3b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charge2"",
                    ""type"": ""Button"",
                    ""id"": ""6d364d36-86a5-4b21-831d-c48f45bdd781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charge3"",
                    ""type"": ""Button"",
                    ""id"": ""ec95d18e-4783-4332-a1ce-870bf5f2cfbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Charge4"",
                    ""type"": ""Button"",
                    ""id"": ""5f73f688-42b7-49df-9056-cdae14e82691"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4c893f65-a185-4a66-af50-ce800ef3819d"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""efa548e6-2dcd-4a40-b657-edb3de3a4d5a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""11d14841-0647-414f-bcea-25bc5aca5ff8"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4311fc2a-6d1e-408c-857f-ece9f1cc0a66"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d72ae9f4-00cc-447a-b6ba-7e2aa195180e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2d029d0-ec3c-4506-8290-c1e30044f325"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftStickX"",
                    ""id"": ""c8a37e24-0ef0-4075-a96b-655c2c733f5a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a416124a-828c-49eb-b19e-e0e8ff57ae42"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6a0382a0-edcb-4dba-90b0-556b0679e150"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Move2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c1c2a4de-7ae1-435f-8919-34b745f60c16"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Jump2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""628ff77c-908a-4df8-b046-4a7c5601d9bd"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Drop2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6161220-c685-4839-b79a-52d7f527ded9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Fire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftStickX"",
                    ""id"": ""74921476-e928-434e-b9eb-77c8fb6ca473"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5f026a79-4054-42b9-8346-85857264eca2"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Move3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b2b39e6d-f1ca-4cfc-a22e-0f2801b259a0"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Move3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""17708944-288d-4eb0-bc08-27ca59343639"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Jump3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bebb833-193a-414a-9e3e-5dfada655d35"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Drop3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e4a54ae-166a-4c90-8bc5-194cabf01ae6"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Fire3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""RightStick"",
                    ""id"": ""75a50636-057d-4a20-8280-10d5dcfa5dde"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""60a36ba2-181d-4fc6-a73b-6c8e41fb6062"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Aim2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""95490c22-0b22-42b3-b31b-6e7e5d5e5bc1"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Aim2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9caa7c16-95a4-4e32-83c7-abec7a24bce2"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Aim2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6a75218d-899a-4b23-87a3-d8864c5fa71a"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Aim2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""id"": ""92ba081c-7d23-49e4-ab18-8edb33d6c340"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""db9c3c6f-2ee4-4228-9f19-68b86fa428ea"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Aim3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d07f1d75-7648-411c-bbaa-711c00cf63af"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Aim3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd210a03-f0c8-4462-aeb4-04659d9385b4"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Aim3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b8814586-8175-407a-9e88-481a080f5c99"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Aim3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStickX"",
                    ""id"": ""a94a0cab-1349-4f57-af8e-d66751e982f5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dd930be7-ab44-429b-9c5c-8fb0be700ea7"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Move4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d707a69e-3951-4280-9bd6-b1707c0b3663"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Move4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""id"": ""ea39cf02-7b24-4e36-97e3-c0790a5f8423"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4c3b4a85-acde-4c0e-933c-65c8cb721a4b"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Aim4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b73fc10f-a7cb-46f8-9591-8fdc26952afa"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Aim4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a0d1f620-d8d4-4341-a4c2-97a5f5369572"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Aim4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""86597be6-10ce-4c69-bd18-b5090cb461d8"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Aim4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""de434094-d211-43e6-86a2-fc2a4c94c58d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Jump4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a42fbca-0c85-4498-adc9-c73ea25f38fd"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Drop4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b2560bd-5e78-451d-9acb-95028a4d844b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Fire4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""RightStick"",
                    ""id"": ""6504fc47-2f0b-4dd9-b82f-5bf1f0452934"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b922d938-b0f7-45ea-b0ed-0add992e2bac"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e21eb0e7-6de0-4097-9301-43fa7a69c4e9"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""87644c38-83eb-41a2-87d2-0c0d37595b5f"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""78527749-43d7-4cf3-b8f0-ed2f77a1b8a4"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6e3f57f7-2200-4a2e-ba34-8d83d9c8644e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Hold(duration=0.5,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Charge1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af8814bf-5aef-40cb-8f5a-058fe96f36d5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Hold(duration=0.5,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": ""Controller2"",
                    ""action"": ""Charge2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbd12442-36b6-4515-a786-35e015717b1e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Hold(duration=0.5,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": ""Controller3"",
                    ""action"": ""Charge3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00caabca-6adc-463c-8d0d-29a9b1ecc548"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Hold(duration=0.5,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": ""Controller4"",
                    ""action"": ""Charge4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller2"",
            ""bindingGroup"": ""Controller2"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller3"",
            ""bindingGroup"": ""Controller3"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller4"",
            ""bindingGroup"": ""Controller4"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Move2 = m_Player.FindAction("Move2", throwIfNotFound: true);
        m_Player_Move3 = m_Player.FindAction("Move3", throwIfNotFound: true);
        m_Player_Move4 = m_Player.FindAction("Move4", throwIfNotFound: true);
        m_Player_Aim = m_Player.FindAction("Aim", throwIfNotFound: true);
        m_Player_Aim2 = m_Player.FindAction("Aim2", throwIfNotFound: true);
        m_Player_Aim3 = m_Player.FindAction("Aim3", throwIfNotFound: true);
        m_Player_Aim4 = m_Player.FindAction("Aim4", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Jump2 = m_Player.FindAction("Jump2", throwIfNotFound: true);
        m_Player_Jump3 = m_Player.FindAction("Jump3", throwIfNotFound: true);
        m_Player_Jump4 = m_Player.FindAction("Jump4", throwIfNotFound: true);
        m_Player_Drop = m_Player.FindAction("Drop", throwIfNotFound: true);
        m_Player_Drop2 = m_Player.FindAction("Drop2", throwIfNotFound: true);
        m_Player_Drop3 = m_Player.FindAction("Drop3", throwIfNotFound: true);
        m_Player_Drop4 = m_Player.FindAction("Drop4", throwIfNotFound: true);
        m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
        m_Player_Fire2 = m_Player.FindAction("Fire2", throwIfNotFound: true);
        m_Player_Fire3 = m_Player.FindAction("Fire3", throwIfNotFound: true);
        m_Player_Fire4 = m_Player.FindAction("Fire4", throwIfNotFound: true);
        m_Player_Charge1 = m_Player.FindAction("Charge1", throwIfNotFound: true);
        m_Player_Charge2 = m_Player.FindAction("Charge2", throwIfNotFound: true);
        m_Player_Charge3 = m_Player.FindAction("Charge3", throwIfNotFound: true);
        m_Player_Charge4 = m_Player.FindAction("Charge4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Move2;
    private readonly InputAction m_Player_Move3;
    private readonly InputAction m_Player_Move4;
    private readonly InputAction m_Player_Aim;
    private readonly InputAction m_Player_Aim2;
    private readonly InputAction m_Player_Aim3;
    private readonly InputAction m_Player_Aim4;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Jump2;
    private readonly InputAction m_Player_Jump3;
    private readonly InputAction m_Player_Jump4;
    private readonly InputAction m_Player_Drop;
    private readonly InputAction m_Player_Drop2;
    private readonly InputAction m_Player_Drop3;
    private readonly InputAction m_Player_Drop4;
    private readonly InputAction m_Player_Fire;
    private readonly InputAction m_Player_Fire2;
    private readonly InputAction m_Player_Fire3;
    private readonly InputAction m_Player_Fire4;
    private readonly InputAction m_Player_Charge1;
    private readonly InputAction m_Player_Charge2;
    private readonly InputAction m_Player_Charge3;
    private readonly InputAction m_Player_Charge4;
    public struct PlayerActions
    {
        private @PlayerInputs m_Wrapper;
        public PlayerActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Move2 => m_Wrapper.m_Player_Move2;
        public InputAction @Move3 => m_Wrapper.m_Player_Move3;
        public InputAction @Move4 => m_Wrapper.m_Player_Move4;
        public InputAction @Aim => m_Wrapper.m_Player_Aim;
        public InputAction @Aim2 => m_Wrapper.m_Player_Aim2;
        public InputAction @Aim3 => m_Wrapper.m_Player_Aim3;
        public InputAction @Aim4 => m_Wrapper.m_Player_Aim4;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Jump2 => m_Wrapper.m_Player_Jump2;
        public InputAction @Jump3 => m_Wrapper.m_Player_Jump3;
        public InputAction @Jump4 => m_Wrapper.m_Player_Jump4;
        public InputAction @Drop => m_Wrapper.m_Player_Drop;
        public InputAction @Drop2 => m_Wrapper.m_Player_Drop2;
        public InputAction @Drop3 => m_Wrapper.m_Player_Drop3;
        public InputAction @Drop4 => m_Wrapper.m_Player_Drop4;
        public InputAction @Fire => m_Wrapper.m_Player_Fire;
        public InputAction @Fire2 => m_Wrapper.m_Player_Fire2;
        public InputAction @Fire3 => m_Wrapper.m_Player_Fire3;
        public InputAction @Fire4 => m_Wrapper.m_Player_Fire4;
        public InputAction @Charge1 => m_Wrapper.m_Player_Charge1;
        public InputAction @Charge2 => m_Wrapper.m_Player_Charge2;
        public InputAction @Charge3 => m_Wrapper.m_Player_Charge3;
        public InputAction @Charge4 => m_Wrapper.m_Player_Charge4;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove2;
                @Move2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove2;
                @Move2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove2;
                @Move3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove3;
                @Move3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove3;
                @Move3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove3;
                @Move4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove4;
                @Move4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove4;
                @Move4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove4;
                @Aim.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim2;
                @Aim2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim2;
                @Aim2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim2;
                @Aim3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim3;
                @Aim3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim3;
                @Aim3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim3;
                @Aim4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim4;
                @Aim4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim4;
                @Aim4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim4;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump2;
                @Jump2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump2;
                @Jump2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump2;
                @Jump3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump3;
                @Jump3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump3;
                @Jump3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump3;
                @Jump4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump4;
                @Jump4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump4;
                @Jump4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump4;
                @Drop.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop;
                @Drop2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop2;
                @Drop2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop2;
                @Drop2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop2;
                @Drop3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop3;
                @Drop3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop3;
                @Drop3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop3;
                @Drop4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop4;
                @Drop4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop4;
                @Drop4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDrop4;
                @Fire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire2;
                @Fire2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire2;
                @Fire2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire2;
                @Fire3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire3;
                @Fire3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire3;
                @Fire3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire3;
                @Fire4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire4;
                @Fire4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire4;
                @Fire4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire4;
                @Charge1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge1;
                @Charge1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge1;
                @Charge1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge1;
                @Charge2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge2;
                @Charge2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge2;
                @Charge2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge2;
                @Charge3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge3;
                @Charge3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge3;
                @Charge3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge3;
                @Charge4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge4;
                @Charge4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge4;
                @Charge4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCharge4;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Move2.started += instance.OnMove2;
                @Move2.performed += instance.OnMove2;
                @Move2.canceled += instance.OnMove2;
                @Move3.started += instance.OnMove3;
                @Move3.performed += instance.OnMove3;
                @Move3.canceled += instance.OnMove3;
                @Move4.started += instance.OnMove4;
                @Move4.performed += instance.OnMove4;
                @Move4.canceled += instance.OnMove4;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Aim2.started += instance.OnAim2;
                @Aim2.performed += instance.OnAim2;
                @Aim2.canceled += instance.OnAim2;
                @Aim3.started += instance.OnAim3;
                @Aim3.performed += instance.OnAim3;
                @Aim3.canceled += instance.OnAim3;
                @Aim4.started += instance.OnAim4;
                @Aim4.performed += instance.OnAim4;
                @Aim4.canceled += instance.OnAim4;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Jump2.started += instance.OnJump2;
                @Jump2.performed += instance.OnJump2;
                @Jump2.canceled += instance.OnJump2;
                @Jump3.started += instance.OnJump3;
                @Jump3.performed += instance.OnJump3;
                @Jump3.canceled += instance.OnJump3;
                @Jump4.started += instance.OnJump4;
                @Jump4.performed += instance.OnJump4;
                @Jump4.canceled += instance.OnJump4;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
                @Drop2.started += instance.OnDrop2;
                @Drop2.performed += instance.OnDrop2;
                @Drop2.canceled += instance.OnDrop2;
                @Drop3.started += instance.OnDrop3;
                @Drop3.performed += instance.OnDrop3;
                @Drop3.canceled += instance.OnDrop3;
                @Drop4.started += instance.OnDrop4;
                @Drop4.performed += instance.OnDrop4;
                @Drop4.canceled += instance.OnDrop4;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @Fire2.started += instance.OnFire2;
                @Fire2.performed += instance.OnFire2;
                @Fire2.canceled += instance.OnFire2;
                @Fire3.started += instance.OnFire3;
                @Fire3.performed += instance.OnFire3;
                @Fire3.canceled += instance.OnFire3;
                @Fire4.started += instance.OnFire4;
                @Fire4.performed += instance.OnFire4;
                @Fire4.canceled += instance.OnFire4;
                @Charge1.started += instance.OnCharge1;
                @Charge1.performed += instance.OnCharge1;
                @Charge1.canceled += instance.OnCharge1;
                @Charge2.started += instance.OnCharge2;
                @Charge2.performed += instance.OnCharge2;
                @Charge2.canceled += instance.OnCharge2;
                @Charge3.started += instance.OnCharge3;
                @Charge3.performed += instance.OnCharge3;
                @Charge3.canceled += instance.OnCharge3;
                @Charge4.started += instance.OnCharge4;
                @Charge4.performed += instance.OnCharge4;
                @Charge4.canceled += instance.OnCharge4;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    private int m_Controller2SchemeIndex = -1;
    public InputControlScheme Controller2Scheme
    {
        get
        {
            if (m_Controller2SchemeIndex == -1) m_Controller2SchemeIndex = asset.FindControlSchemeIndex("Controller2");
            return asset.controlSchemes[m_Controller2SchemeIndex];
        }
    }
    private int m_Controller3SchemeIndex = -1;
    public InputControlScheme Controller3Scheme
    {
        get
        {
            if (m_Controller3SchemeIndex == -1) m_Controller3SchemeIndex = asset.FindControlSchemeIndex("Controller3");
            return asset.controlSchemes[m_Controller3SchemeIndex];
        }
    }
    private int m_Controller4SchemeIndex = -1;
    public InputControlScheme Controller4Scheme
    {
        get
        {
            if (m_Controller4SchemeIndex == -1) m_Controller4SchemeIndex = asset.FindControlSchemeIndex("Controller4");
            return asset.controlSchemes[m_Controller4SchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMove2(InputAction.CallbackContext context);
        void OnMove3(InputAction.CallbackContext context);
        void OnMove4(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnAim2(InputAction.CallbackContext context);
        void OnAim3(InputAction.CallbackContext context);
        void OnAim4(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnJump2(InputAction.CallbackContext context);
        void OnJump3(InputAction.CallbackContext context);
        void OnJump4(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnDrop2(InputAction.CallbackContext context);
        void OnDrop3(InputAction.CallbackContext context);
        void OnDrop4(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnFire2(InputAction.CallbackContext context);
        void OnFire3(InputAction.CallbackContext context);
        void OnFire4(InputAction.CallbackContext context);
        void OnCharge1(InputAction.CallbackContext context);
        void OnCharge2(InputAction.CallbackContext context);
        void OnCharge3(InputAction.CallbackContext context);
        void OnCharge4(InputAction.CallbackContext context);
    }
}
